// Reference documents: public sources (sources.ts, generated by .research/merge.py)
// and internal client rules, fictional for demo purposes.

import { sourceDocuments } from "./sources";
import type { CategoryId, Importance, RegionId } from "./taxonomy";

export type Doc = {
  id: string;
  title: string;
  category: CategoryId;
  importance: Importance;
  summary: string;
  body: string[];
  keywords: string[];
  // Scope: an absent field means 'applies to all'.
  scope: {
    sectors?: string[];
    roles?: string[];
    regions?: RegionId[];
    provinces?: string[];
    workTimes?: string[];
    contractTypes?: string[];
    companies?: string[];
  };
  // Trust signals
  source: string;
  url?: string;
  owner: { name: string; team: string };
  lastValidated: string; // ISO date
  status: "valide" | "obsolete" | "a-verifier";
  replacedBy?: string;
  conflictsWith?: string[];
};

const internalDocuments: Doc[] = [
  // --- Internal policies ---------------------------------------------------
  {
    id: "interne-fiduciaire-meuse-grille",
    title: "Fiduciaire Meuse: internal salary grid",
    category: "interne",
    importance: "policy",
    summary: "The client pays 5% above sector-standard rates for certified profiles.",
    body: ["Policy agreed with client in 2025: CP 200 rates + 5% for registered chartered accountants."],
    keywords: ["internal grid", "client"],
    scope: { companies: ["fiduciaire-meuse"] },
    source: "Client email · Fiduciaire Meuse file",
    owner: { name: "Thomas Leroy", team: "Payroll Consultant Namur" },
    lastValidated: "2025-08-22",
    status: "valide",
  },
  {
    id: "interne-fiduciaire-meuse-teletravail",
    title: "Fiduciaire Meuse: remote work policy",
    category: "interne",
    importance: "policy",
    summary: "2 days of remote work per week after a 3-month onboarding period.",
    body: ["To mention in the job posting: this is an attraction factor validated by the client."],
    keywords: ["remote work"],
    scope: { companies: ["fiduciaire-meuse"] },
    source: "SharePoint · Clients/Fiduciaire Meuse",
    owner: { name: "Thomas Leroy", team: "Payroll Consultant Namur" },
    lastValidated: "2026-02-10",
    status: "valide",
  },
  {
    id: "interne-bricoplus-recrutement",
    title: "BricoPlus: recruitment validation process",
    category: "interne",
    importance: "policy",
    summary: "All job openings must be validated by the regional director.",
    body: ["The store manager submits the request; the regional director validates within 5 days."],
    keywords: ["validation", "process"],
    scope: { companies: ["brico-plus"] },
    source: "SharePoint · Clients/BricoPlus",
    owner: { name: "An Peeters", team: "Key Account Retail" },
    lastValidated: "2026-03-15",
    status: "valide",
  },
  {
    id: "interne-sdworx-mobilite",
    title: "SD Worx: internal mobility priority",
    category: "interne",
    importance: "policy",
    summary: "Job openings are published internally 10 days before any external distribution.",
    body: ["Publish first on the internal career portal, then on external channels."],
    keywords: ["internal mobility"],
    scope: { companies: ["sdworx"] },
    source: "Intranet · People & Culture",
    owner: { name: "Nadia Benali", team: "Talent Acquisition" },
    lastValidated: "2026-01-20",
    status: "valide",
  },

  {
    id: "demarche-namur-permanence",
    title: "Legal office: Namur branch",
    category: "demarches",
    importance: "guidance",
    summary: "The Namur office holds legal consultations on Thursdays for hiring questions.",
    body: ["Contact: Thomas Leroy. Response within 24 hours for urgent matters."],
    keywords: ["legal office", "contact", "expert"],
    scope: { provinces: ["namur"] },
    source: "Teams · #namur-office",
    owner: { name: "Thomas Leroy", team: "Payroll Consultant Namur" },
    lastValidated: "2026-09-01",
    status: "valide",
  },
];

export const documents: Doc[] = [...sourceDocuments, ...internalDocuments];

export const getDocument = (id: string) => documents.find((d) => d.id === id);
